package com.jdap.auction.patterns.session;

/**
 * Enum description
 *
 */
public enum SessionParam
{
    AUTHORIZATION_USER,
    AUTHORIZATION_SESSION_ID,
    AUTHORIZATION_PRINCIPAL,
    AUTHORIZATION_ROLE,
    AUTHORIZATION_TENANCY,
    AUTHORIZATION_ACTION_TYPE,
    AUTHORIZATION_SKIP_VALIDATION,
    AUTHORIZATION_SKIP_SUBTENANCIES,
    TEMPORALITY_EFF_TS,
    TEMPORALITY_CONTEXT_FORCE,
    TEMPORALITY_CONTEXT_PROJ_ID,
    TEMPORALITY_CONTEXT_TASK_ID,
    TEMPORALITY_CONTEXT_BEGIN_TX,
    TEMPORALITY_CONTEXT_BEGIN_TX_ID,
    TEMPORALITY_CONTEXT_END_TX_ID;
}
