select count(6) from bids;

select * from bids;
SELECT * FROM bidders;

delete bids;
drop table bids;


CREATE TABLE "CDMR"."BIDS"
  (
    "BID_ID"     NUMBER(19,0) NOT NULL ENABLE,
    "BID_AMOUNT" NUMBER(19,4),
    "BID_DATE" TIMESTAMP (6),
    "BIDDER_ID" NUMBER(19,0),
    "ITEM_ID"   NUMBER(19,0),
    PRIMARY KEY ("BID_ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "CDMR_TABLESPACE" ENABLE
  )
  SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  
  CREATE TABLE "CDMR"."BID"
  (
    "BIDAMOUNT" NUMBER(19,4),
    "BIDDATE" TIMESTAMP (6),
    "BIDDERID" NUMBER(19,0),
    "ITEMID"   NUMBER(19,0),
    "LASTMODIFIED" TIMESTAMP (6),
    "VERSION"        NUMBER(19,0),
    "OID"            VARCHAR2(36 BYTE),
    PRIMARY KEY ("OID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "CDMR_TABLESPACE" ENABLE
  )
  SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )

  
CREATE TABLE "CDMR"."SEQUENCE"
  (
    "SEQ_COUNT" NUMBER(38,0),
    "SEQ_NAME"  VARCHAR2(50 BYTE) NOT NULL ENABLE,
    PRIMARY KEY ("SEQ_NAME") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "CDMR_TABLESPACE" ENABLE
  )
  SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "CDMR_TABLESPACE" ;  