<?xml version="1.0" encoding="UTF-8"?>
<!--
** This WSDL defines the Search enterprise service interface. 
 
 WSDL File Name 
 Name: \\ApplicationConnectorServiceLibrary\CPS\Search\V1\SearchProviderABCSTransportV1.wsdl 
 -->

<definitions 
	xmlns="http://schemas.xmlsoap.org/wsdl/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:com="http://xmlns.avocent.com/auction/EnterpriseObjectLibrary/Common/V1" 
	xmlns:ebo="http://xmlns.avocent.com/auction/EnterpriseObjectLibrary/CPS/Search/V1"
	xmlns:abcs="http://xmlns.avocent.com/auction/ABCSLibrary/CPS/Search/V1/SearchProvABCSTransport"
	xmlns:svcdoc="http://xmlns.oracle.com/Services/Documentation/V1" 
	name="SearchProviderABCSTransportV1" 
	targetNamespace="http://xmlns.avocent.com/auction/ABCSLibrary/CPS/Search/V1/SearchProvABCSTransport">

	<types>
		<xsd:schema 
			targetNamespace="http://xmlns.avocent.com/auction/EnterpriseServiceLibrary/CPS/Search/V1"
			elementFormDefault="qualified">

			<xsd:import
				namespace="http://xmlns.avocent.com/auction/EnterpriseObjectLibrary/Common/V1"
				schemaLocation="../../../../../EnterpriseObjectLibrary/Infrastructure/V1/Meta.xsd"/>

			<xsd:import
				namespace="http://xmlns.avocent.com/auction/EnterpriseObjectLibrary/CPS/Search/V1"
				schemaLocation="../../../../../EnterpriseObjectLibrary/CPS/Search/V1/SearchEBM.xsd"/>
		</xsd:schema>
	</types>

	<message name="FaultMsg">
		<part name="Fault" element="com:Fault"/>
	</message>
	<message name="SearchRequestMsg">
		<part name="SearchRequestEBM" element="ebo:SearchRequestEBM"/>
	</message>
	<message name="SearchResponseMsg">
		<part name="SearchResponseEBM" element="ebo:SearchResponseEBM"/>
	</message>	

	<portType name="SearchProviderABCSTransportV1">
		<operation
			name="Search">
			<input message="abcs:SearchRequestMsg"/>
			<output message="abcs:SearchResponseMsg"/>
			<fault name="fault" message="abcs:FaultMsg"/>
		</operation>

	</portType>

</definitions>