//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.04 at 05:50:27 PM EST 
//


package com.jdap.auction.common.xml.apiconfiguration;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ApiFaultType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ApiFaultType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FaultedServiceId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FaultCodeCategory" type="{http://xmlns.jdap.com/Common/Fault/ApiFault/v2}FaultCodeCategory"/>
 *         &lt;element name="FaultCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Message" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FaultTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="SeverityLevel" type="{http://xmlns.jdap.com/Common/Fault/ApiFault/v2}FaultSeverityLevel"/>
 *         &lt;element name="RequestCorrelationIds" type="{http://xmlns.jdap.com/Common/Fault/ApiFault/v2}RequestCorrelationIdsType" minOccurs="0"/>
 *         &lt;element name="ExceptionAttribute" type="{http://xmlns.jdap.com/Common/Fault/ApiFault/v2}NameValuePairType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Stack" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Extension" type="{http://xmlns.jdap.com/Common/Fault/ApiFault/Extension/v2}ExtensionApiFaultType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ApiFaultType", propOrder = {
    "faultedServiceId",
    "faultCodeCategory",
    "faultCode",
    "message",
    "faultTime",
    "severityLevel",
    "requestCorrelationIds",
    "exceptionAttribute",
    "stack",
    "extension"
})
@XmlRootElement(name = "apiFaultType", namespace = "http://xmlns.jdap.com/Common/Fault/ApiFault/v2")
public class ApiFaultType {

    @XmlElement(name = "FaultedServiceId", required = true)
    protected String faultedServiceId;
    @XmlElement(name = "FaultCodeCategory", required = true)
    protected FaultCodeCategory faultCodeCategory;
    @XmlElement(name = "FaultCode", required = true)
    protected String faultCode;
    @XmlElement(name = "Message", required = true)
    protected String message;
    @XmlElement(name = "FaultTime", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar faultTime;
    @XmlElement(name = "SeverityLevel", required = true)
    protected FaultSeverityLevel severityLevel;
    @XmlElement(name = "RequestCorrelationIds")
    protected RequestCorrelationIdsType requestCorrelationIds;
    @XmlElement(name = "ExceptionAttribute", type = NameValuePairType.class)
    protected List<NameValuePairType> exceptionAttribute;
    @XmlElement(name = "Stack", type = String.class)
    protected List<String> stack;
    @XmlElement(name = "Extension")
    protected ExtensionApiFaultType extension;

    /**
     * Gets the value of the faultedServiceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFaultedServiceId() {
        return faultedServiceId;
    }

    /**
     * Sets the value of the faultedServiceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFaultedServiceId(String value) {
        this.faultedServiceId = value;
    }

    /**
     * Gets the value of the faultCodeCategory property.
     * 
     * @return
     *     possible object is
     *     {@link FaultCodeCategory }
     *     
     */
    public FaultCodeCategory getFaultCodeCategory() {
        return faultCodeCategory;
    }

    /**
     * Sets the value of the faultCodeCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link FaultCodeCategory }
     *     
     */
    public void setFaultCodeCategory(FaultCodeCategory value) {
        this.faultCodeCategory = value;
    }

    /**
     * Gets the value of the faultCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFaultCode() {
        return faultCode;
    }

    /**
     * Sets the value of the faultCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFaultCode(String value) {
        this.faultCode = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessage(String value) {
        this.message = value;
    }

    /**
     * Gets the value of the faultTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFaultTime() {
        return faultTime;
    }

    /**
     * Sets the value of the faultTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFaultTime(XMLGregorianCalendar value) {
        this.faultTime = value;
    }

    /**
     * Gets the value of the severityLevel property.
     * 
     * @return
     *     possible object is
     *     {@link FaultSeverityLevel }
     *     
     */
    public FaultSeverityLevel getSeverityLevel() {
        return severityLevel;
    }

    /**
     * Sets the value of the severityLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link FaultSeverityLevel }
     *     
     */
    public void setSeverityLevel(FaultSeverityLevel value) {
        this.severityLevel = value;
    }

    /**
     * Gets the value of the requestCorrelationIds property.
     * 
     * @return
     *     possible object is
     *     {@link RequestCorrelationIdsType }
     *     
     */
    public RequestCorrelationIdsType getRequestCorrelationIds() {
        return requestCorrelationIds;
    }

    /**
     * Sets the value of the requestCorrelationIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestCorrelationIdsType }
     *     
     */
    public void setRequestCorrelationIds(RequestCorrelationIdsType value) {
        this.requestCorrelationIds = value;
    }

    /**
     * Gets the value of the exceptionAttribute property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the exceptionAttribute property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExceptionAttribute().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NameValuePairType }
     * 
     * 
     */
    public List<NameValuePairType> getExceptionAttribute() {
        if (exceptionAttribute == null) {
            exceptionAttribute = new ArrayList<NameValuePairType>();
        }
        return this.exceptionAttribute;
    }

    /**
     * Gets the value of the stack property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stack property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStack().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getStack() {
        if (stack == null) {
            stack = new ArrayList<String>();
        }
        return this.stack;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionApiFaultType }
     *     
     */
    public ExtensionApiFaultType getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionApiFaultType }
     *     
     */
    public void setExtension(ExtensionApiFaultType value) {
        this.extension = value;
    }

}
