//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.04 at 05:50:27 PM EST 
//


package com.jdap.auction.common.xml.apiconfiguration;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FaultCodeCategory.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FaultCodeCategory">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Business"/>
 *     &lt;enumeration value="System"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FaultCodeCategory")
@XmlEnum
public enum FaultCodeCategory {


    /**
     * Fault is associated with a business exception/error.
     * 
     */
    @XmlEnumValue("Business")
    BUSINESS("Business"),

    /**
     * Fault is associated with a system exception/error.
     * 
     */
    @XmlEnumValue("System")
    SYSTEM("System");
    private final String value;

    FaultCodeCategory(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FaultCodeCategory fromValue(String v) {
        for (FaultCodeCategory c: FaultCodeCategory.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
