<?xml version="1.0" encoding="UTF-8"?>

<definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://facade.alarms.ejb.services.cps.commonplatform.avocent.com/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/"
	targetNamespace="http://facade.alarms.ejb.services.cps.commonplatform.avocent.com/"
	name="AppsDeviceAlarmStatusServiceBeanService">
	<types>
		<xsd:schema>
			<xsd:import
				namespace="http://facade.alarms.ejb.services.cps.commonplatform.avocent.com/"
				schemaLocation="../../../../EnterpriseObjectLibrary/Apps/AlarmsAndEvents/V1/AppsDeviceAlarmStatusServiceBeanService.xsd" />
		</xsd:schema>
	</types>
	<message name="evaluateStateChange">
		<part name="parameters" element="tns:evaluateStateChange" />
	</message>
	<message name="evaluateStateChangeResponse">
		<part name="parameters" element="tns:evaluateStateChangeResponse" />
	</message>
	<message name="CdmException">
		<part name="fault" element="tns:CdmException" />
	</message>
	<message name="MissingDataException">
		<part name="fault" element="tns:MissingDataException" />
	</message>
	<portType name="AppsDeviceAlarmStatusServiceBeanService">
		<operation name="evaluateStateChange">
			<input message="tns:evaluateStateChange" />
			<output message="tns:evaluateStateChangeResponse" />
			<fault message="tns:CdmException" name="CdmException" />
			<fault message="tns:MissingDataException" name="MissingDataException" />
		</operation>
	</portType>
	<binding name="AppsDeviceAlarmStatusServiceBeanServicePortBinding"
		type="tns:AppsDeviceAlarmStatusServiceBeanService">
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http"
			style="document" />
		<operation name="evaluateStateChange">
			<soap:operation soapAction="" />
			<input>
				<soap:body use="literal" />
			</input>
			<output>
				<soap:body use="literal" />
			</output>
			<fault name="CdmException">
				<soap:fault name="CdmException" use="literal" />
			</fault>
			<fault name="MissingDataException">
				<soap:fault name="MissingDataException" use="literal" />
			</fault>
		</operation>
	</binding>
	<service name="AppsDeviceAlarmStatusServiceBeanService">
		<port name="AppsDeviceAlarmStatusServiceBeanServicePort"
			binding="tns:AppsDeviceAlarmStatusServiceBeanServicePortBinding">
			<soap:address
				location="http://10.207.66.166:8001/AppsDeviceAlarmStatusServiceBean/AppsDeviceAlarmStatusServiceBeanService" />
		</port>
	</service>
</definitions>