<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://event.ds.auction.avocent.com/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://event.ds.auction.avocent.com/"
	name="EventServiceBeanService">
	<types>
		<xsd:schema>
			<xsd:import namespace="http://event.ds.auction.avocent.com/"
				schemaLocation="../../../../EnterpriseObjectLibrary/Apps/AlarmsAndEvents/V1/EventServiceBeanService.xsd" />
		</xsd:schema>
	</types>
	<message name="createEvent">
		<part name="parameters" element="tns:createEvent" />
	</message>
	<message name="createEventResponse">
		<part name="parameters" element="tns:createEventResponse" />
	</message>
	<portType name="EventServiceBeanService">
		<operation name="createEvent">
			<input message="tns:createEvent" />
			<output message="tns:createEventResponse" />
		</operation>
	</portType>
</definitions>