package com.jdap.auction.patterns;

/**
 *
 * Interface file to specify a simple UUID generator for
 * the system. An interface was chosen, so the implementation
 * could be changed or injected via Spring.
 **/

public interface OIDGeneratorInterface
{
   /**
   *  Override this method to produce a different UUID generator.
   *
   * @return - UUID generated by the method.
   */
   
   public OID generateOID();
}
