<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://ejb.service.notification.apps.auction.avocent.com/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/"
	targetNamespace="http://ejb.service.notification.apps.auction.avocent.com/"
	name="NotificationSchedularService">
	<types>
		<xsd:schema>
			<xsd:import
				namespace="http://ejb.service.notification.apps.auction.avocent.com/"
				schemaLocation="../../../../EnterpriseObjectLibrary/Apps/Notification/V1/NotificationAlarmDto.xsd" />
		</xsd:schema>
	</types>
	<message name="schedule">
		<part name="parameters" element="tns:schedule" />
	</message>
	<portType name="NotificationSchedularService">
		<operation name="schedule">
			<input message="tns:schedule" />
		</operation>
	</portType>
</definitions>