<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions
	targetNamespace="http://xmlns.avocent.com/auction/EnterpriseObjectLibrary/CPS/Common/V1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:tns="http://xmlns.avocent.com/auction/EnterpriseServiceLibrary/CPS/V1"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
	xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
	xmlns:cpscom="http://xmlns.avocent.com/auction/EnterpriseObjectLibrary/CPS/Common/V1"
	xmlns:com="http://xmlns.avocent.com/auction/EnterpriseObjectLibrary/Common/V1">
	<wsdl:types>
		<xsd:schema
			targetNamespace="http://xmlns.avocent.com/auction/EnterpriseObjectLibrary/CPS/Common/V1"
			elementFormDefault="qualified">
			<xsd:include
				schemaLocation="../../../../EnterpriseObjectLibrary/CPS/Common/V1/FilePurgeEBM.xsd" />
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="FilePurgeReqMsg">
		<wsdl:part name="FilePurgeRequest" element="cpscom:FilePurgeRequestEBM" />
	</wsdl:message>
	<wsdl:message name="FilePurgeResMsg">
		<wsdl:part name="FilePurgeResponse" element="cpscom:FilePurgeResponseEBM" />
	</wsdl:message>
	<wsdl:portType name="FilePurgeV1">
		<wsdl:operation name="purgeData">
			<wsdl:input message="cpscom:FilePurgeReqMsg" />
			<wsdl:output message="cpscom:FilePurgeResMsg" />
		</wsdl:operation>
	</wsdl:portType>
</wsdl:definitions>
